@extends('layouts.frontend-master')

@section('content')
    <section class="mt-4">
        <div class="container">
            <div class="partners">
            <h4 class="page-header mb-3">Terms - Users</h4>


              <div class="accordion" id="accordionExample">
                <div class="card">
                  <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                      <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                       Contract
                      </button>
                    </h2>
                  </div>

                  <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>By using or visiting website, mobile applications, software, data feeds, and services provided to you (collectively the&nbsp;<strong>"Service"&nbsp;</strong>) you signify your agreement to these terms and conditions (the "Terms of Service") and privacy policy (the&nbsp;<strong>&ldquo;Privacy Policy&rdquo;&nbsp;</strong>) of the Company. If you do not agree to any of these terms, please do not use the Service.</p>
                      <p><strong>Welcome to ReraAgents.in!&nbsp;</strong>We are a digital real estate advertising / marketing and information services platform connecting people with the real estate market. ReraAgents.in and our subsidiaries and affiliates (collectively the &ldquo;Company&rdquo; or&nbsp;<strong>"ReraAgents.in"&nbsp;</strong>) provide you with access to a variety of services, including but not limited to the www.ReraAgents.in website (the&nbsp;<strong>"Website"&nbsp;</strong>) and ReraAgents.in's mobile applications (the&nbsp;<strong>&ldquo;Mobile App&rdquo;&nbsp;</strong>) and all the products and services available through our Website and Mobile App (collectively the&nbsp;<strong>"Services"</strong>). The Website and Mobile App is owned and operated by Charanetra Spaces Private Limited, a company incorporated under the laws of India.</p>
                      <p>These &lsquo;Terms of Use&rsquo; constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                    </div>
                  </div>
                </div>


                <div class="card">
                  <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        To whom does this policy apply?
                      </button>
                    </h2>
                  </div>
                  <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Some parts of this Policy are directed at specific types of people. We use some special terminology to refer to them, which we define below. This Policy applies to everyone who uses our Services, but sometimes we direct parts of it toward particular groups of users.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><strong><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Users / Customers:</span></strong><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">&nbsp;"Users / Customers" are everyone who uses our Services.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><strong><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333; background: white;">RERA Certified Agents, Agents, and Brokers:</span></strong><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333; background: white;">&nbsp;we refer <strong>RERA Certified Agents, Agents, and Brokers</strong> as Agents who uses our services</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><strong><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Builders:</span></strong><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">&nbsp;Builders who access our services </span></p>
                    </div>
                  </div>
                </div>


                <div class="card">
                  <div class="card-header" id="headingThree">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        What information do we collect, and where do we get it from?
                      </button>
                    </h2>
                  </div>
                  <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body">
                     <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">We collect information from everyone who uses our Services: Like many online services, we use technologies like session and persistent cookies, log data, and third-party analytics services to collect and analyze information about all users of our Services. This includes things like User search preferences, interaction with ads on our Services, and location.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Our servers automatically record information&nbsp;<strong>("Log Data")&nbsp;</strong>created by your use of the Services. Log Data may include information such as your IP address, browser type, operating system, the referring web page, pages visited, location, your mobile carrier, device, search terms, and cookie information. We receive Log Data when you interact with our Services, for example, when you visit our Website and / or Mobile App, sign into our Services, or interact with our email notifications. We use Log Data to provide our Services and to measure, customize, and improve them, as well as collect and use them in the aggregate. This policy does not apply to, nor do we take any responsibility for any information that is collected by any third party either using the Services or through any links on the Website and / or Mobile App or through any of the advertisements.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Cookies are small data files that we transfer to your computer. We use "session" cookies to keep you logged in while you use our Services, to better understand how you interact with our Services, and to monitor aggregate usage and web traffic information on our Services. We use "persistent" cookies to recognize you each time you return to our Services. For example, we create a persistent cookie that includes some basic information about you, like your most recent search and whether an agent responded to a query you sent using ReraAgents.in's Services. We use this persistent cookie to remember your preferences and, if you create an account, to make your user experience consistent after you register.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Most internet browsers automatically accept cookies, but you can change your settings or use third-party tools to refuse cookies or prompt you before accepting cookies from the websites you visit. You can also use your browser settings or other tools to delete cookies you already have. Please be aware that some parts of our Services may not work for you if you disable cookies.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Information we collect from Agents, users, customers, Builders: If you create a account with us, we will ask you to provide certain information in order to set up your account. We ask all users to provide details including but not limited to your name, your company name (if available), phone number, email address and details of the property to be uploaded on the Website etc. we require you to submit all of the information including but not limited to as required from landlords and agents as well as a description of your campaign and/or your property details. We may also collect addresses from all users, so that we can process the notifications when there is deals in your Country, State, &amp; City. A ReraAgents.in representative may call you to verify your information.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Additional information about you that we obtain from third parties: We may sometimes obtain information about you from third parties and use it to serve you better. For example, our partners may help us provide predictions of your income range and how likely you may be to purchase a home. We will share this augmented data only with our Agnets who we assume can fulfill your requirements</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Location Data: If you provide location information (like a ZIP code, street address, or even just a city) during the registration process or at any other time via your account settings, we will store that information and associate it with your account. We may use and store information about your location to provide localized features, to analyze our Services with the help of third-party analytics services, to provide you with relevant advertising and marketing recommendations, and otherwise to improve and customize our Services.</span></p>
                    </div>
                  </div>
                </div>


                 <div class="card">
                  <div class="card-header" id="headingFour">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                        Why we collect information from you?
                      </button>
                    </h2>
                  </div>
                  <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                    <div class="card-body">
                    <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">ReraAgents.in provides digital real estate advertising / marketing / Sales and information services through its Website or its offices located in various city&rsquo;s, Mobile App and other services. To provide our Services, we use the information we collect to:</span></p>
                    <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Help you find the most relevant information for your situation by customizing our Services to optimize your experience.</span></p>
                    <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Keep you connected with ReraAgents.in, RERA Certified Agents, Agents</span></p>
                    <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Put you in touch with the right people to sell, buy, rent, or research residential real estate, obtain a mortgage, avail related services and to optimize the information we share with those parties to initiate a productive and efficient relationship</span></p>
                    </div>
                  </div>
                </div>


                 <div class="card">
                  <div class="card-header" id="headingFive">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                        Services Description?
                      </button>
                    </h2>
                  </div>
                  <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>ReraAgents.in and its offices attempts to be as accurate as possible. However, ReraAgents.in does not warrant that descriptions of or content of this site is accurate, complete, reliable, current, or error-free. Also, your access to the Services may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction. ReraAgents.in provides links to other sites over which ReraAgents.in has no control. ReraAgents.in is not responsible for the availability of such external sites or resources and does not endorse and is not responsible or liable for any content, advertising, products or other material on or available from such sites or resources.</p>
                      <p>From time to time, we share the information of those who access our Services with the other reputable organizations whose products or services we think you might find interesting and suits to your requirements. If you do not want us to share your information with other companies or organizations, please let us know by emailing us at support@ReraAgents.in.</p>
                      <p>Persons who supply us with their telephone numbers on-line may receive telephone calls or text messages from us with information regarding new products or services or upcoming events. You hereby give specific consent to receive the telephone calls or text messages related to our Services in case you are using our services. If you do not wish to receive such telephone calls or text messages, please let us know by e-mailing us at support@ReraAgents.in.</p>
                      <p>With respect to Ad servers: To try and bring you offers that are of interest to you, we have relationships with other companies to whom we allow to place ads on our Website and Mobile App. As a result of your visit to our Website and / or Mobile App, ad server companies may collect information such as your domain type, your IP address and clickstream information.</p>
                      <p>Direct contact with users, Agents RERA Certified Agents, Customers: If you post a property or requirement or any finance request you agreed to receive calls via our Services and Agents, RERA Certified Agents, we may share personally identifiable information that you share with us and information about your use of our Services with the party you wanted to contact. This may include data you input such as home search criteria or Log Data that we collect as you use the Services. &nbsp;Finance/Loan services: If you request a mortgage quote using our services, you authorize us to share the personally identifiable information necessary for our partners to deliver the service. They are not permitted to use the information for any other purpose.</p>
                      <p>User-Generated Content: If you use our user-generated content services, like posting a question, answer or blog on our Website and / or Mobile App, you should be aware that any personally identifiable information you submit there can be read, collected, or used by other users and could be used to send you unsolicited messages. We are not responsible for the personally identifiable information you choose to submit in these forums. Further we are also not responsible for the comments or remarks posted by users in those forums etc. and therefore recommend you to perform your own diligence before relying on any such information.</p>
                      <p>If you are a verified rights owner and want to report a listing issue, you may report support@ReraAgents.in</p>
                    </div>
                  </div>
                </div>



                 <div class="card">
                  <div class="card-header" id="headingSix">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                        Representations and Warranties by Agents
                      </button>
                    </h2>
                  </div>
                  <div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#accordionExample">
                    <div class="card-body">
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">By registering and/or listing any properties on our Website and / or Mobile App, each Agent represents and warrants that:</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">(a) The Agents have all rights to list the said properties on the Website and / or Mobile App, and by doing so, the Agents are not violating or infringing upon the rights (including the intellectual property rights) of any other person and any applicable laws.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">(b) Agents are complying with all the regulatory requirements including the provisions of Real Estate Regulatory Authorities Act 2016 in regard to the services / products they are offering via this platform and the listings / advertisements they are posting on this platform.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">(c) All the details of the properties listed on the Platform, shared by the Agents, are current, up-to-date and accurate, including the location, property specifications and price.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">(d) By listing the properties on the Website and / or Mobile App, the Agents is granting all such rights to ReraAgents.in to authorise ReraAgents.in to use and/or share such listing details in any manner, including on any other websites, platforms etc. of ReraAgents.in or any associate or third party.</span></p>
                    </div>
                  </div>
                </div>

                 <div class="card">
                  <div class="card-header" id="headingSeven">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                        Disclaimers related to completeness and authenticity of the content / listings
                      </button>
                    </h2>
                  </div>
                  <div id="collapseSeven" class="collapse" aria-labelledby="headingSeven" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>ReraAgents.in does not take responsibility or liability for the actions, products, content and services on the Website and / or Mobile App, if any, which are linked to Affiliates and / or third party websites using APIs or otherwise. ReraAgents.in will not be liable for any damages of any kind arising out of or relating to the use or the inability to use its Website and / or Mobile App, its content or links, including but not limited to damages caused by or related to errors, omissions, interruptions, defects, delay in operation or transmission, computer virus, line failure and all other direct, indirect, special, incidental, punitive, loss of profit, exemplary or consequential damages whether based on warranty, contract, tort or any other legal theory including Force Majeure, and whether or not, such organizations or entities were intimated or advised of the possibility of such damages. You agree to defend, indemnify, and hold harmless, ReraAgents.in and/ or its associates, subsidiaries, their officers, directors, employees, affiliates, licensees, business partners and agents, from and against any claims, actions or demands, including without limitation reasonable legal and accounting fees, alleging or resulting from your use of any material or your breach of these terms and conditions or any applicable law.</p>
                      <p>ReraAgents.in website does not facilitate or participate in any manner in the process of selling, buying, renting etc. of properties, and it is not responsible for any dealing, negotiations, transactions, etc. whatsoever between the parties connected through our Services, including and not limited to any quality assurance, guarantee, claim etc. given by one party to another in any transaction. ReraAgents.in will not be party to any legal proceedings between parties contracted through these Services. In case ReraAgents.in is sought to be implicated in any legal proceedings, costs will be recovered from the party that names ReraAgents.in as a party to such proceedings.</p>
                      <p>ReraAgets.in offices As a RERA certified Agent in the respective state does facilitate or participate in the process of selling, buying etc. the office is responsible for dealing when a customer or agent walks into the office and does negotiations, transactions etc., whatsoever between the parties connected through our office services</p>
                      <ol>
                      <li>The user should conduct checks and establish authenticity of any property, or project, its title, built up area, suitability for buying / renting in a form and manner deemed appropriate at his or her cost.</li>
                      <li>ReraAgents.in being an advertising platform does not and cannot validate the authenticity of content in its Services. A lot of content is uploaded by the advertiser and we do not filter or verify the same. If a complaint is made, we will take remedial measures.</li>
                      <li>Certain points to bear in mind:</li>
                      </ol>
                      <p>(a) Conduct a comprehensive check of ownership to verify owners' / landlords&rsquo; credentials.</p>
                      <p>(b) Visit the project site/property personally, to ensure that the seller&rsquo;s / landlord&rsquo;s claim is genuine and that the property is not an 'imaginary' one.</p>
                      <p>(c) Beware of false title documents. Loans may have been secured against properties that may be disputed or have remained vacant for long.</p>
                      <p>(d) We strongly recommend that proper due diligence on the property is conducted prior to entering into a transaction related to a real estate.</p>
                      <p>(e) It should be independently ensured by the User whether the seller is complying with the provisions of Real Estate Regulatory Authorities and its applicability to the relevant property or project.</p>
                      <p>ReraAgents.in is an advertising and marketing platform to many developer for their real estate projects (hereinafter referred to as &ldquo;Project&rdquo;) andis in no way facilitating, negotiating or assisting in the sales between you and the developer. While displaying this information on our Website / Mobile App, ReraAgents.in is relying on the information as provided by the Developer of such Project. Before making any decision please ensure to validate all the information and go through the terms and conditions as included in the documents. Further:</p>
                      <ol>
                      <li>While reasonable efforts are being made to ensure the meaningful information being displayed by the Agents and the same being asked to be updated by Agents on regular intervals, there is a possibility that the information displayed may not be current and complete.</li>
                      <li>The pictures / photos shown here include artist&rsquo;s impression of the Project. The actual properties may vary from such representations.</li>
                      <li>Users should verify the completeness and accuracy of all such information from the RERA website, as may be applicable, of respective States where the Project is registered. ReraAgents.in does not, by any means verify, validate, endorse or promote the compliance of a specific Project with the RERA regulations.</li>
                      <li>Please make sure you verify all the details independently from the Agents or from the RERA website before making any decision in relation to the purchase of the properties.</li>
                      </ol>
                      <p>There is also a lot of information displayed on the platform which is neither an advertisement / listing as provided by Agents and is collated by our research team from the publically available information and is meant to be a tool for the Users&rsquo; own research and awareness about real estate market. While reasonable efforts are being made to ensure the completeness of such information being displayed here and the same being updated on regular intervals by our research team, there is a possibility that the information displayed is not current and complete. This information shall in no way be considered as an advertisement or offer to sale from the Agents or ReraAgents.in. ReraAgents.in shall neither be responsible nor liable for any inaccuracy in the information provided here and therefore the Users are requested to independently validate the information from the respective developers before making their decision for purchase of properties. ReraAgents.in, its directors, employees, agents and other representatives shall not be liable for any action taken, cost / expenses / losses incurred, by you, based on the information given on the portal.</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="headingEight">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                        Copyright and Trademark policy
                      </button>
                    </h2>
                  </div>
                  <div id="collapseEight" class="collapse" aria-labelledby="headingEight" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>All content included in our Services, such as text, graphics, logos, button icons, images, clips, digital downloads, data compilations, and software, is the property of the Company, its Users and its content suppliers and protected by copyright laws. All software used on this Website and Mobile App is the property of the Company..</p>
                      <p>All other trademarks not owned by Company that appear on this site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by ReraAgents.in or its affiliates.</p>
                      <p>ReraAgents.in is committed to removing infringing products from its platform. To facilitate this, ReraAgents.in has put in place a ReraAgents.in Infringement Verification process so that intellectual property owners could easily report listings that infringe their rights. We understand that it is in ReraAgents.in interest to ensure that infringing products are removed from its platform, as they erode Buyer and Seller trust.</p>
                      <p>If you are a verified rights owner and want to report a listing issue, you may report support@ReraAgents.in</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="headingNine">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                        General Matters
                      </button>
                    </h2>
                  </div>
                  <div id="collapseNine" class="collapse" aria-labelledby="headingNine" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>The accuracy and confidentiality of your account information is your responsibility: You are responsible for maintaining the secrecy and accuracy of your password, email address, and other account information at all times. We recommend a strong password that you do not use with other services. We are not responsible for personal data transmitted to a third party as a result of an incorrect email address or loss of passwords from you</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="headingTen">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTen" aria-expanded="false" aria-controls="collapseTen">
                        Third-Party Websites
                      </button>
                    </h2>
                  </div>
                  <div id="collapseTen" class="collapse" aria-labelledby="headingTen" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>Our Website / Mobile App may contain links to other websites. When you click on one of these links, you are navigating to another website. We do not accept liability for misuse of any information by any website controller to which we may link. We also do not have any responsibility of liability for the content on websites that use the ReraAgents.in search functionality. We encourage you to read the privacy statements of these websites, which may differ from ours.</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="headingEleven">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseEleven" aria-expanded="false" aria-controls="collapseEleven">
                        Sale/Merger
                      </button>
                    </h2>
                  </div>
                  <div id="collapseEleven" class="collapse" aria-labelledby="headingEleven" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>Information about our Users and our Website / Mobile App is a business asset of ReraAgents.in. Consequently, information about our Users, including personal information, will be disclosed as part of any merger or acquisition, creation of a separate business to provide the Website, our Services or fulfill products, sale or pledge of company assets as well as in the event of an insolvency, bankruptcy or receivership in which personal information would be transferred as one of the business assets of the company.</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="headingTwelve">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwelve" aria-expanded="false" aria-controls="collapseTwelve">
                        Indemnification and Limitation of Liability
                      </button>
                    </h2>
                  </div>
                  <div id="collapseTwelve" class="collapse" aria-labelledby="headingTwelve" data-parent="#accordionExample">
                    <div class="card-body">
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Each User agrees to indemnify, defend and hold harmless the Company and its affiliates including but not limited to its (and its affiliates&rsquo;) officers, directors, consultants, agents and employees (&ldquo;Indemnities&rdquo;) from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by the Indemnities that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by such User pursuant to these General Terms of Use. Further, each User agrees to hold the Indemnities harmless against any claims made by any third party due to, or arising out of, or in connection with, such User&rsquo;s use of the Website or Services, User&rsquo;s violation of the General Terms of Use, or User&rsquo;s violation of any rights of another, including any intellectual property rights.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">In no event shall the Indemnities, be liable to the Users or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not the Company has been advised of the possibility of such damages, arising out of or in connection with (i) User&rsquo;s use of or access to the Website, Services or materials on the Website; or (ii) services provided by any Registered Service Provider</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">The limitations and exclusions in this Section apply to the maximum extent permitted by applicable laws.</span></p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading13">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse13" aria-expanded="false" aria-controls="collapse13">
                        Amendment to Terms of Service
                      </button>
                    </h2>
                  </div>
                  <div id="collapse13" class="collapse" aria-labelledby="heading13" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to you. It is your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Services following the posting of changes will mean that you accept and agree to the revisions.</p>
                    </div>
                  </div>
                </div>


                <div class="card">
                  <div class="card-header" id="heading14">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse14" aria-expanded="false" aria-controls="collapse14">
                        Arbitration
                      </button>
                    </h2>
                  </div>
                  <div id="collapse14" class="collapse" aria-labelledby="heading14" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>If any dispute arises between a user/users and ReraAgents.in arising out of use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of these terms and conditions, the dispute shall be referred to a sole Arbitrator who shall be an independent and neutral third party identified by ReraAgents.in. Decision of the Arbitrator shall be final and binding on both the parties to the dispute. The place of arbitration shall be Guntur, Andhra Pradesh. </p>
                    </div>
                  </div>
                </div>


                <div class="card">
                  <div class="card-header" id="heading15">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse15" aria-expanded="false" aria-controls="collapse15">
                        Grievance Redressal Mechanism
                      </button>
                    </h2>
                  </div>
                  <div id="collapse15" class="collapse" aria-labelledby="heading15" data-parent="#accordionExample">
                    <div class="card-body">
                      <p>Any complaints, abuse or concerns with regards to content and or comment or breach of these terms shall be immediately informed to the Grievance Officer through email on the following email Id. support@ReraAgents.in. Any grievance so received by the Company shall be resolved within the best possible time.</p>
                    </div>
                  </div>
                </div>


                <h4 class="page-header mt-5 mb-3">Terms - Agents</h4>

                <div class="card">
                  <div class="card-header" id="heading16">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse16" aria-expanded="false" aria-controls="collapse16">
                        Contract
                      </button>
                    </h2>
                  </div>
                  <div id="collapse16" class="collapse" aria-labelledby="heading16" data-parent="#accordionExample">
                    <div class="card-body">
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">This is a Contract/Agreement between you("Agent or Agent or RERA Certified Agent") and Charanetra Spaces Private Limited having its registered office at 4-5-29/119B, Vidyanagar 3rd line Guntur, 522007 Andhara Pradesh, INDIA (hereinafter referred as "Company" /Reraagents.in/ "we" in this agreement.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">This Contract is effective from the date when you signup on Reraagents.in or its all sources Reraagents.in website or Reraagents Mobile Application.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Reraagents.in provides easy way of connecting to other individual sellers or Agents or RERA Agents in desired location of your choice, </span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Reraagents.in provides marketing and lead generation services and other connected services without any specific warranty of any specific result/outcome.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Reraagents.in may modify this Agreement from time to time at its own discretion. The modification in any Contract term shall be updated by us from time to time. The modification shall be effective from the time it is updated on the website and mobile Application. It is your responsibility to check the provisions of this Contract regularly. Your use of Reraagents.in site implies your acceptance of any change in this Contract as effected from time to time by Reraagents.in.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">THIS CONTRACT LIMITS OUR LIABILITY AND ALSO LIMITS YOUR REMEDIES. </span></p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading17">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse17" aria-expanded="false" aria-controls="collapse17">
                        Who is eligible?
                      </button>
                    </h2>
                  </div>
                  <div id="collapse17" class="collapse" aria-labelledby="heading17" data-parent="#accordionExample">
                    <div class="card-body">
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">You can become a member or Agent on Reraagents.in by successfully registering on the website www.reraagents.in or its mobile Application of www.Reraagents.in. For using this resources you must be eligible to enter into, execute and abide the terms of this contract as per the applicable laws of India. Your registration on Reraagents.in will mean that that you will abide by all of the terms of this Agreement.</span></p>
                      <p style="background: white; margin: 10.5pt 0in 10.5pt 0in;"><span style="font-size: 10.5pt; font-family: 'Segoe UI',sans-serif; color: #333333;">Reraagents.in will be entitled to restrict/change/terminate this agreement at its own discretion with or without any notice to you. Access rights to the Reraagents.in services may also be withdrawn.</span></p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading19">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse19" aria-expanded="false" aria-controls="collapse19">
                        FreeConsent
                      </button>
                    </h2>
                  </div>
                  <div id="collapse19" class="collapse" aria-labelledby="heading19" data-parent="#accordionExample">
                    <div class="card-body">
                    <p> You agree with a sound mind, without undue force, pressure or coercion on you - that your registration as a Agent on Reraagents.in is your complete unqualified acceptance, relating to various terms detailed in this Agreement. You further undertake that in case of any dispute relating to this Contract the exclusive jurisdiction to file law suits against you shall be in the courts at GUNTUR only.</p>
                    </div>
                  </div>
                </div>


                <div class="card">
                  <div class="card-header" id="heading20">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse20" aria-expanded="false" aria-controls="collapse20">
                        Listings / Agents / Rera Agents Data
                      </button>
                    </h2>
                  </div>
                  <div id="collapse20" class="collapse" aria-labelledby="heading20" data-parent="#accordionExample">
                    <div class="card-body">
                       <p>  You agree to deliver to Reraagents.in, via an interface determined by Reraagents.in and in a format and language specified by Reraagents.in, You further confirm that you have full authority to publish the Listings on Reraagents.in.</p>
                        <p>As a quality check we have every right to verify the details of the property published by you.</p>

                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading21">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse21" aria-expanded="false" aria-controls="collapse21">
                        License
                      </button>
                    </h2>
                  </div>
                  <div id="collapse21" class="collapse" aria-labelledby="heading21" data-parent="#accordionExample">
                    <div class="card-body">
                     <p> You hereby grant the Company and its affiliates a worldwide, royalty free, non-exclusive, irrevocable license to use, display and archive your Listings on any and all websites owned or operated or controlled - in whole or in part -by Reraagents.in or its subsidiaries (collectively known as "Platform") including without Reraagents.in.</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading22">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse22" aria-expanded="false" aria-controls="collapse22">
                        ReraAgent or RERA Certified Agents.in services
                      </button>
                    </h2>
                  </div>
                  <div id="collapse22" class="collapse" aria-labelledby="heading22" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>Upon registration as a Agent on Reraagents.in you will get free listing services which shall include the following:</p>
                      <ol>
                      <li>You will be entitled to post unlimited number of property listings and your or your clients requirements on the website:</li>
                      <li>in may connect you to the RERA Certified Agent in respective state who are interested in any of the property listings posted by you on the Platform;</li>
                      <li>in gives lot of attention to the quality of Agent conduct on its Platform. Therefore, Reraagents.in may record and review the property posted by all. This information may be used for selling the property by any reraagents.in office located in various city&rsquo;s.</li>
                      <li>in may use your posting information in many ways for your posted property sale</li>
                      <li>To reduce the load of unwanted call to you, we are permitting only RERA AGENTS who are certified to view your contact number, however we have no guarantee that RERA Certified Agents share your contact number to the people who they wanted</li>
                      <li>Apart from the RERA Certified Agents who are authorized to call you upon their certificate verification completed by reraagents.in, we reraagents.in may call you from various offices when there is a requirement from various customers who walked into the reraagents.in office</li>
                      <li>in may notify you on different properties on your city&rsquo;s, or state or Country.</li>
                      </ol>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading23">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse23" aria-expanded="false" aria-controls="collapse23">
                        RERA Certificate
                      </button>
                    </h2>
                  </div>
                  <div id="collapse23" class="collapse" aria-labelledby="heading23" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>Reraagents.in may ask you to upload your RERA Agent Certificate which you received on successful registration as Agent in your STATE RERA office. </p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading24">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse24" aria-expanded="false" aria-controls="collapse24">
                        Acknowledgement
                      </button>
                    </h2>
                  </div>
                  <div id="collapse24" class="collapse" aria-labelledby="heading24" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>On completion of the registration process and by accepting the terms of this Agreement, Agent hereby acknowledges:</p>
                      <ol>
                      <li>in ensures that only good quality content is uploaded on the Platform for the users / Agents / RERA Agents. For this purpose Reraagents.in may decide to review the content of every listings provided by the Agent and modify them to make more sense before they are made live on the Platform.</li>
                      <li>in shall have the right to use the listings content provided by the Agent and the listings may be shown to the customers who walked into the offices located in different city&rsquo;s;</li>
                      <li>in gives lot of attention to quality of information submitted by the Agent and reserves the right to remove content that does not meet quality parameters;</li>
                      <li>Users of Reraagents.in shall be encourage to walk into the offices located nearest to you for better property advise ;</li>
                      <li>To proactively inform Reraagents.in within 7 days upon successful completion of the transaction with a customer referred by Reraagents.in;</li>
                      <li>That any listing content provided by the Agent shall be removed from the Platform after 90 days (or after a period as Reraagents.in may deem necessary) to ensure only active listings are shown to the users of Reraagents.in;</li>
                      <li>in does not give any kind of assurance / guarantee on the volume of calls or volume of sales</li>
                      </ol>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading25">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse25" aria-expanded="false" aria-controls="collapse25">
                        Suspension of Service
                      </button>
                    </h2>
                  </div>
                  <div id="collapse25" class="collapse" aria-labelledby="heading25" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>Reraagents.in also reserves the right to suspend the service if the Agent does not satisfy the quality and conduct guidelines referred in T&C or if the feedback from the other agents or users or RERA certified agents are not good</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading26">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse26" aria-expanded="false" aria-controls="collapse26">
                        Term & Termination
                      </button>
                    </h2>
                  </div>
                  <div id="collapse26" class="collapse" aria-labelledby="heading26" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>This Agreement will remain in full force and effect after you have completed the registration as a Agent on Reraagents.in. Reraagents.in reserves its right to change the Service(s) or delete features at any time and for any reason and to cancel or suspend your access at any time. Such cancellation or suspension may be without cause and/or without notice. In case of Service cancellation, your right to use the Service ceases right away. You understand that Reraagents.in may at any time, at its sole discretion and without prior notice to you, prohibit or restrict your access to the use of any or all the Services of Reraagents.in.
                      <br>You may decide to terminate this Agreement by disabling your login on the Platform. In the event of such a termination you shall remain liable to pay for the Service Charges already accrued or as may be accrued in future due to closure of transaction with the customers referred by Reraagents.in
                      </p>
                    </div>
                  </div>
                </div>

                 <div class="card">
                  <div class="card-header" id="heading27">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse27" aria-expanded="false" aria-controls="collapse27">
                        Other Terms of Use
                      </button>
                    </h2>
                  </div>
                  <div id="collapse27" class="collapse" aria-labelledby="heading27" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>In case of content/data/information submitted by you to Reraagents.in, for availing the Services provided by Reraagents.in, is found incorrect, misleading, derogatory, illegal and/or such content are submitted without any authority then Reraagents.in reserves its rights to take appropriate legal actions including cancellation of any or all your registrations with or without any notice to you in this regard.</p>
                      <p>You will not use any information obtained from the Site/Service in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to any person without their prior explicit consent.</p>
                      <p>In order to protect Reraagents.in and/or its users from any abuse / misuse, Reraagents.in reserves the right to restrict the use of Reraagents.in by you for such period which Reraagents.in deems appropriate in its sole discretion.</p>
                      <p>You cannot use any automated processes, including IRC Bots, Robots, Spiders, Scrappers, EXE's, CGI or any other programs/scripts to view and collect information or content on or communicate/contact/respond/interact with Reraagents.in and/or its users unless specifically permitted by Reraagents.in</p>
                      <p>You hereby confirm that the Content posted by you on the site does not contain viruses or other similar harmful or deleterious programming routines. If you violate this provision you may be penalized and including termination of your rights to use the service and any other remedies available to Reraagents.in by law;</p>
                      <p>Reraagents.in may verify the registration Data provided by you through its own sources and/or by asking documentary proof for any such information submitted by you during registration or thereafter (any time). If you provide any information that is untrue, inaccurate, not current or incomplete, or Reraagents.in has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Reraagents.in has rights to suspend or terminate your account and refuse any and all current or future use of the Reraagents.in site and its services (or any portion thereof). Reraagents.in owns and retains all proprietary rights, including without limitation, all intellectual property rights in the Reraagents.in Site and the Reraagents.in Service;</p>
                      <p>The Site contains the copyrighted material, trademarks, and other proprietary information of Reraagents.in, and its licensors. Except for that information which is in the public domain or for which you have been given express permission by Reraagents.in, you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information;</p>
                      <p>All lawful, legal and non-objectionable messages (in the sole discretion of Reraagents.in), content and/or other information, content or material that you post on the forum boards shall become the property of Reraagents.in. Reraagents.in reserves the right to scrutinize all such information, content and/or material posted on the forum boards and shall have the exclusive right to either remove, edit and/or display such information, material and/or content;</p>
                      <p>As a user of the platform you further agree to be abide by:</p>
                      <ol>
                      <li>Privacy policy of Reraagents.in</li>
                      <li>Terms of usage of Reraagents.in</li>
                      </ol>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading28">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse28" aria-expanded="false" aria-controls="collapse28">
                        Indemnity
                      </button>
                    </h2>
                  </div>
                  <div id="collapse28" class="collapse" aria-labelledby="heading28" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>You agree to indemnify and hold Reraagents.in, its subsidiaries, directors, affiliates, officers, Agent or RERA Certified Agents, and other partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorney's fees, made by any third party due to or arising out of your use of the Reraagents.in Services in violation of this Agreement and/or arising from a breach of any of the terms of this Agreement and/or any breach of your representations and warranties set forth above.</p>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <div class="card-header" id="heading29">
                    <h2 class="mb-0">
                      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse29" aria-expanded="false" aria-controls="collapse29">
                        Applicable Laws
                      </button>
                    </h2>
                  </div>
                  <div id="collapse29" class="collapse" aria-labelledby="heading29" data-parent="#accordionExample">
                    <div class="card-body">
                     <p>The Parties agree that all matters related to this Agreement shall be governed by the Laws of India each Party irrevocably consents to the exclusive jurisdiction of the state of Haryana with respect to any action brought in connection with this Agreement.</p>
                    </div>
                  </div>
                </div>
                
              </div>
            </div>
        </div>
    </section>
@endsection